### PR TITLE
Added API URL endpoint (group g)

### PR DESCRIPTION
**Pull request by MathiasHoeyrup**

### CODE REVIEW

**Comment by HelgeCPH** [comment]
Hej,

It seems to me as if you are working on an old version of the file `repositories.py`. Since last week it looks as in the following:

```
    [
        "group g",
        "LearnIT > GitHub",
        ["https://github.itu.dk/mahn/OneDevOps"],
        "http://<minitwit_application_url>",
        "http://<sim_api_url>",
    ],
```

I do not know if the URL `http://104.248.246.24` that you sent in this pull request points to the application or to the simulator API.

Please send a new pull request.

**Comment by MathiasHoeyrup** [comment]
Hey Helge,

The URL 104.248.246.24 points to the API.

We are experiencing troubles with setting up CI/CD with the repository
we've stated (https://github.itu.dk/mahn/OneDevOps).
It seems Travis and GitHub Actions are not a fan of a repo living in ITU
sub-domain/server whatever.
We unfortunately have to copy everything over to a new repo. I will send a
new pull request later today, with this new one, URL to application and URL
to API.

Are we in a hurry? Or is just some time today fine?

- Mathias
Group g

Den man. 24. feb. 2020 kl. 12.31 skrev Helge <notifications@github.com>:

**Comment by MathiasHoeyrup** [comment]
Hello again,

We are still unsure how we want to do it with GitHub repository now that we
were forced to change. I hope it is okay we are one more day on the way.
I will not make a pull request with information about application and API
URL as I would have to send one more again when we change repo.

I hope it is okay.

- Mathias

Den man. 24. feb. 2020 kl. 12.31 skrev Helge <notifications@github.com>:

**Comment by HelgeCPH** [comment]
Yep okay. Just send one once you are done.

**Pull request closed without merging**
